#!/bin/bash

# Goal: Write a shell script that asks the user to type a word in,
# then tells the user how long that word is. (read, wc)

echo "Please type a single word. The program then tells you how long it is."
read inputWord
noWords=$(echo ${inputWord} | wc -m)
let noWords=noWords-1
echo "The typed word has ${noWords} characters."
