#!/bin/bash

# Goal: Write a shell script called which lists just the directories in the current directory (test).
# Modified to list directoires in test_input directory

location=/Users/jacekdabrowski/Desktop/shell_ex/ex_4/test_input
cd $location

for file in $(ls); do
  if test -d ${location}/${file}; then
    echo $file
  fi
done
