#!/bin/bash

# Goal: Write a shell script called see taking a filename as argument
# which uses ls if the file's a directory and more if the file's otherwise (test)

# Inform if no argument ientered
if [[ $# -eq 0 ]]; then
  echo "You have not entered any filename. Plese do so."

# Providing that the argument is directory, list the content otherwise use more
elif test -d $1; then
  ls $1

elif !(test -d $1); then
  more $1
fi
