#!/bin/bash

# Goal: Read in two numbers from the keyboard and print
# their sum (see the read, echo and let commands in the shell manual page).

echo "Type two numbers, each followed by ENTER."
read num1
read num2
echo "The first typed number is ${num1}, the second one is ${num2}."
let sum=$num1+$num2
echo "The sum of the numbers is ${sum}."
