#!/bin/bash

# Goal: Suppose that you want to write the same letter to many people
# except that you want each letter addressed to the senders personally.
# This mailmerge facility can be created using a shell script.
# Put the names of the recipients (one per line) in a file called names,
# create a texfile called template which has NAME wherever you want
# the person's name to appear and write a script (using sed) to produce
# a temporary file called letter from the template file.


nameFielePath="./names"
templateFielPath="./template"
noCreatedMails=0

while read -r line
do
  let noCreatedMails=noCreatedMails+1
  sed "s/NAME/$line/g" ${templateFielPath} > mail_${noCreatedMails}
done < "$nameFielePath"
