#!/bin/bash

# Goal: Write a shell script that takes a uid as an argument and prints
# out that person's name, home directory, shell and group number.
# Print out the name of the group corresponding to the group number,
# and other groups that person may belong to.

# Constarint: The script is targeted to MacOS's users

userName=$(id -nu $1)
echo "Person's name:"$(dscl . -read /Users/$userName RealName | cut -d ":" -f 2-)
echo "Home directory:"$(dscl . -read /Users/$userName NFSHomeDirectory | cut -d ":" -f 2-)
echo "Shell:"$(dscl . -read /Users/$userName UserShell | cut -d ":" -f 2-)
echo "Primary group number:"$(dscl . -read /Users/$userName PrimaryGroupID | cut -d ":" -f 2-)
echo "Groups' names the person belongs to: " $(id -Gn $1)
