#!/bin/bash

# Goal: Change the args script supplied earlier so that if no argument is provided,
# "They are'' isn't printed, and if exactly 1 argument is provided,
# "... 1 argument'' rather than "... 1 arguments'' is printed (use if)

if [[ $# -eq 0 ]]; then
  echo "No arguments provided."
elif [[ $# -gt 0 ]]; then
  echo "The $0 command has $# arguments. The argument are: $*"
fi
